---
- name: using different modules
  hosts: all
  tasks:
    - name: install git
      apt:
        name: git
        state: present
    - name: install apache
      apt:
        name: apache2
        state: present
    - name: create file
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

